const express=require('express')
const cors=require('cors')
const app = express();
app.use(express.json())
app.use(cors())
require('dotenv').config();
const passport = require("passport");
require("../middleware/passport_setup")
const userRoutes=require('./UserRegistration')
const userSiginRoutes=require('./UserSignin')
const authGoogle=require("./authGoogle")
const profileRoutes=require("./dating/profile")
const employementRoutes=require("./dating/employement")
const locationRoutes=require("./dating/locationSave")
const sameInterestRoutes=require('./dating/sameInterest')
const profileView=require("./dating/userProfileView")
const doNotShowRoutes=require("./dating/doNotShow")
const requestRoutes=require('./dating/request')
const conversationRoutes=require('./dating/conversation')
const messageRoutes=require('./dating/message')
const chatListRoutes=require("./dating/chatList")
const sentListRoutes=require("./dating/sent")
const shortListRoutes=require("./dating/shortList")
const accpetListRoutes=require("./dating/accept")
const ReceivedRoutes=require('./dating/recieved')
const RejectRoutes=require("./dating/reject")

const CategoryRoutes=require('./ecommerce/category')
const ItemRoutes=require('./ecommerce/item')
const CartRoutes=require('./ecommerce/cart')
const AddressRoutes=require('./ecommerce/address')
const RazorPayRoutes=require('./ecommerce/razorPay')
const OrderRoutes=require('./ecommerce/order')
app.use(express.json());
app.use(passport.initialize());

app.use("/",authGoogle)
app.use('/',userRoutes)
app.use('/',userSiginRoutes)
app.use("/",profileRoutes)
app.use("/",employementRoutes)
app.use("/",locationRoutes)
app.use("/",sameInterestRoutes)
app.use("/",profileView)
app.use("/",doNotShowRoutes)
app.use("/",requestRoutes)
app.use('/',conversationRoutes)
app.use('/',messageRoutes)
app.use("/",chatListRoutes)
app.use("/",sentListRoutes)
app.use("/",shortListRoutes)
app.use("/",accpetListRoutes)
app.use("/",ReceivedRoutes)
app.use("/",RejectRoutes)
//ecommerce routes
app.use('/ecommerce',CategoryRoutes)
app.use('/ecommerce',ItemRoutes)
app.use('/ecommerce',CartRoutes)
app.use('/ecommerce',AddressRoutes)
app.use("/",RazorPayRoutes)
app.use('/ecommerce',OrderRoutes)
module.exports=app